# Welcome to Jekyll!
#

# Site settings
title: Lionwol
description: |small biography page about me
  crafted by [HTML5 UP](http://html5up.net)
owner: Lionowl # or company name
first_published: 2018 # if migrating another site, the year of your first publish
email: lionowl.training@gmail.com
baseurl: "home" # the subpath of your site, e.g. /blog
url: "http://www.lionowl.com" # the base hostname & protocol for your site
social:
  #linkedin-square:
  #facebook-official:
  #google-plus-square:
  #email: /contact/
  #flickr:
  instagram-square: https://www.instagram.com/lionowl.training
  #youtube-square:
  #spotify:
  #stack-overflow:
  #vimeo:
  #reddit:
  #stubleupon:
  #delicious:
  #pied-piper:
  #digg:
  #soundcloud:
  #deviantart:
  #angellist:
  #tumblr-square:
  #stackexchange:
  #weibo:
  #trello:
  #foursquare:
  #linux:
  #bitbucket-square:
  #vk:
  #slack:
  #vine:
  #weixin:
  #yelp:
  #skyatlas:
  #leanpub:
  #connectdevelop:
  #ils:
  #forumbee:
  #tripadvisor:
  #amazon:

# Build settings
markdown: kramdown
#sass:
#  style: compressed
